package Worker;



import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import Login.LoginGUI;
import functions.*;

import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class CMusteriSDGUI extends javax.swing.JDialog {
    DefaultTableModel model;
    WorkerOperations islemler = new WorkerOperations();
    CustomerOperations musteriIslem = new CustomerOperations();
    int id;
    /**
     * Creates new form CMusteriSDGUI
     */
    public CMusteriSDGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel)table.getModel();
        calisanGoruntule();
        setTitle("Müşteri silme ve güncelleme");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        geri_butonu = new javax.swing.JButton();
        geri_butonu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		CalisanGUI calisanGUI = new CalisanGUI();
				calisanGUI.setVisible(true);
				dispose();
        	}
        });
        cikis_butonu = new javax.swing.JButton();
        cikis_butonu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		LoginGUI lGUI = new LoginGUI();
				lGUI.setVisible(true);
				dispose();
        	}
        });
        ad_alani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        soyad_alani = new javax.swing.JTextField();
        telNo_alani = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KrediBorcu_alani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ParaBirimi_alani = new javax.swing.JTextField();
        bakiye_alani = new javax.swing.JTextField();
        silme_butonu = new javax.swing.JButton();
        guncelleme_butonu = new javax.swing.JButton();
        mesaj_alani = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Soyad", "Telefon no", "bakiye", "Kredi Borcu", "Para birimi", "Mt ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        geri_butonu.setText("Geri");

        cikis_butonu.setText("Çıkış");

        jLabel1.setText("Ad:");

        soyad_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyad_alaniActionPerformed(evt);
            }
        });

        jLabel2.setText("Soyad:");

        jLabel3.setText("Tel no:");

        jLabel5.setText("Kredi Borcu:");

        jLabel7.setText("Para Birimi:");

        jLabel4.setText("Bakiye:");

        silme_butonu.setBackground(new java.awt.Color(204, 204, 204));
        silme_butonu.setText("Sil");
        silme_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silme_butonuActionPerformed(evt);
            }
        });

        guncelleme_butonu.setBackground(new java.awt.Color(204, 204, 204));
        guncelleme_butonu.setText("Güncelle");
        guncelleme_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleme_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(soyad_alani)
                    .addComponent(telNo_alani))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ParaBirimi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(KrediBorcu_alani)
                    .addComponent(bakiye_alani))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guncelleme_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(silme_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mesaj_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(geri_butonu)
                        .addGap(18, 18, 18)
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cikis_butonu)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arama_cubugu)
                    .addComponent(geri_butonu)
                    .addComponent(cikis_butonu))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KrediBorcu_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silme_butonu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(ParaBirimi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelleme_butonu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(bakiye_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(mesaj_alani)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soyad_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyad_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyad_alaniActionPerformed

    private void silme_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silme_butonuActionPerformed
        mesaj_alani.setText("");
        
        int selectedrow = table.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesaj_alani.setText("Musteriler tablosu şuanda boş...");
            }else{
                mesaj_alani.setText("Lüfen silinecek bir Müşteri seçin...");                  
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow,0);
            islemler.musteriSilme(id);
            calisanGoruntule();
            mesaj_alani.setText("Müşteri başarıyla silindi...");
        }
    }//GEN-LAST:event_silme_butonuActionPerformed
    
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selectedrow = table.getSelectedRow();
        id = (int)model.getValueAt(selectedrow,0);
        ad_alani.setText(model.getValueAt(selectedrow,1).toString());// modele git yani tabloya secilen sutundaki ilk alanı al ad_alanina yaz
        soyad_alani.setText(model.getValueAt(selectedrow,2).toString());
        telNo_alani.setText(model.getValueAt(selectedrow,3).toString());
        bakiye_alani.setText(model.getValueAt(selectedrow,4).toString());
        KrediBorcu_alani.setText(model.getValueAt(selectedrow, 5).toString());
        ParaBirimi_alani.setText(model.getValueAt(selectedrow, 6).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void guncelleme_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleme_butonuActionPerformed
        mesaj_alani.setText("");
        Customer musteri;
        
        musteri = musteriIslem.musteriBilgileriniGetir(id);
        
        int Mt_id = musteri.getMt_id();
        String tc = musteri.getTc();
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String telNo = telNo_alani.getText();
        int bakiye = Integer.parseInt(bakiye_alani.getText());
        int krediBorcu = Integer.parseInt(KrediBorcu_alani.getText());
        String paraBirimi = ParaBirimi_alani.getText();
        
        
        int selectedrow = table.getSelectedRow(); // sectiğimiz satırı aldik
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesaj_alani.setText("Müşteri tablosu şuanda boş...");
            }else{
                mesaj_alani.setText("Lüfen güncellenecek bir Müşteri seçin...");                  
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow,0);
            
            islemler.musteriGuncelleme(id, ad, soyad,telNo,tc,bakiye,krediBorcu,paraBirimi);
            calisanGoruntule();
            mesaj_alani.setText("Müşteri başarıyla güncellendi...");
        }
        
    }//GEN-LAST:event_guncelleme_butonuActionPerformed
    
    public void calisanGoruntule(){
        model.setRowCount(0);  
        
        ArrayList<Customer> musteriler = new ArrayList<Customer>();
        
        musteriler = islemler.SorumluOlduguMusteriler(LoginGUI.calisanId);
        
        if(musteriler != null){
            for(Customer m : musteriler){
                Object[] eklenecek = {m.getId(),m.getAd(),m.getSoyad(),m.getTelno(),m.getBakiye(),m.getKredi_borcu(),m.getPara_birimi(),m.getMt_id()};
                model.addRow(eklenecek);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CMusteriSDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CMusteriSDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CMusteriSDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CMusteriSDGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CMusteriSDGUI dialog = new CMusteriSDGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KrediBorcu_alani;
    private javax.swing.JTextField ParaBirimi_alani;
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField bakiye_alani;
    private javax.swing.JButton cikis_butonu;
    private javax.swing.JButton geri_butonu;
    private javax.swing.JButton guncelleme_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JButton silme_butonu;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTable table;
    private javax.swing.JTextField telNo_alani;
    // End of variables declaration//GEN-END:variables
}
